### ISSUE TITLE
Rubric and Summary

### ISSUE THREAD

**Issue by ulisigi** [benrichard1/capstone#4]
### Criteria 1: HTML Structure  
* _Score Level:_ 4/4
* _Comment(s):_ HTML implementation enables proper use of media queries.

HTML structure reflects the grouping and flow of content in the web browser.
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 2/4
* _Comment(s):_ Desktop AND mobile layout match the wireframe in 2+ sections.
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 3/4
* _Comment(s):_ Media queries kick in at appropriate breakpoints. 

Responsive units are consistently used, but not always. 
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 2/4
* _Comment(s):_ A color palette was chosen OR some typographic considerations were made
 
### Overall Score: 11/16
Your project Meets Expectations - way to go! As mentioned in another part of this review, your layout very closely matched the design spec with a few small differences in the amount of space between elements. Don't forget to add the responsive meta tag to the `<head>` of your HTML! Colmar is the first project to be submitted that allows us the freedom to choose the typography, animations/transitions, and a color palette for our page. You did a nice job matching the design spec, but we'd like to see you incorporate some of these other design decisions to make this project your own. I recommend experimenting with some of these changes and sharing them with your Slack cohort for feedback so you get a better idea of what does or doesn't work when you change colors, text, and animations. 
Overall, you did a nice job with this project. Keep up the great work, and happy coding!

**Comment by benrichard1** [comment]
Thank you for the thorough feedback and resource links.
